# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install
    npm run lint 
    npm test
  displayName: 'npm install, lint, and test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'petfinderbot'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (53cd0336-4079-4703-b33b-28e6a6bd452a)'
    appType: 'functionAppLinux'
    appName: 'petfinder-bot'
    package: '$(Build.ArtifactStagingDirectory)/**/'
    runtimeStack: 'DOCKER|microsoft/azure-functions-node8:2.0'